language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
addons:
  postgresql: 11
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - bundle exec rake db:drop db:create db:schema:load RAILS_ENV=test
script:
  - bundle exec rspec spec --fail-fast
